var_name_to_feat = {
                    # Frequency features
                    'F0semitoneFrom27.5Hz_sma3nz_amean': 'F0 M',
                    'F0semitoneFrom27.5Hz_sma3nz_stddevNorm': 'F0 CV',
                    'F0semitoneFrom27.5Hz_sma3nz_percentile20.0': 'F0 P20',
                    'F0semitoneFrom27.5Hz_sma3nz_percentile50.0': 'F0 P50',
                    'F0semitoneFrom27.5Hz_sma3nz_percentile80.0': 'F0 P80',
                    'F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2': 'F0 P range',
                    'F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope': 'F0 M rising slope',
                    'F0semitoneFrom27.5Hz_sma3nz_stddevRisingSlope': 'F0 SD rising slope',
                    'F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope': 'F0 M falling slope',
                    'F0semitoneFrom27.5Hz_sma3nz_stddevFallingSlope': 'F0 SD falling slope',
                    'loudness_sma3_amean': 'Loudness M',
                    'loudness_sma3_stddevNorm': 'Loudness CV',
                    'loudness_sma3_percentile20.0': 'Loudness P20',
                    'loudness_sma3_percentile50.0': 'Loudness P50',
                    'loudness_sma3_percentile80.0': 'Loudness P80',
                    'loudness_sma3_pctlrange0-2': 'Loudness P range',
                    'loudness_sma3_meanRisingSlope': 'Loudness M rising slope',
                    'loudness_sma3_stddevRisingSlope': 'Loudness SD rising slope',
                    'loudness_sma3_meanFallingSlope': 'Loudness M falling slope',
                    'loudness_sma3_stddevFallingSlope': 'Loudness SD falling slope',
                    'spectralFlux_sma3_amean': 'Spectral flux M',
                    'spectralFlux_sma3_stddevNorm': 'Spectral flux CV',
                    'mfcc1_sma3_amean': 'MFCC1 M',
                    'mfcc1_sma3_stddevNorm': 'MFCC1 CV',
                    'mfcc2_sma3_amean': 'MFCC2 M',
                    'mfcc2_sma3_stddevNorm': 'MFCC2 CV',
                    'mfcc3_sma3_amean': 'MFCC3 M',
                    'mfcc3_sma3_stddevNorm': 'MFCC3 CV',
                    'mfcc4_sma3_amean': 'MFCC4 M',
                    'mfcc4_sma3_stddevNorm': 'MFCC4 CV',
                    'jitterLocal_sma3nz_amean': 'Jitter M',
                    'jitterLocal_sma3nz_stddevNorm': 'Jitter CV',
                    'shimmerLocaldB_sma3nz_amean': 'Shimmer M',
                    'shimmerLocaldB_sma3nz_stddevNorm': 'Shimmer CV',
                    'HNRdBACF_sma3nz_amean': 'Harmonics to noise ratio M',
                    'HNRdBACF_sma3nz_stddevNorm': 'Harmonics to noise ratio CV',
                    'logRelF0-H1-H2_sma3nz_amean': 'H1-H2 M',
                    'logRelF0-H1-H2_sma3nz_stddevNorm': 'H1-H2 CV',
                    'logRelF0-H1-A3_sma3nz_amean': 'H1-A3 M',
                    'logRelF0-H1-A3_sma3nz_stddevNorm': 'H1-A3 CV',
                    'F1frequency_sma3nz_amean': 'F1 frequency M',
                    'F1frequency_sma3nz_stddevNorm': 'F1 frequency CV',
                    'F1bandwidth_sma3nz_amean': 'F1 bandwidth M',
                    'F1bandwidth_sma3nz_stddevNorm': 'F1 bandwidth CV',
                    'F1amplitudeLogRelF0_sma3nz_amean': 'F1 amplitude M',
                    'F1amplitudeLogRelF0_sma3nz_stddevNorm': 'F1 amplitude CV',
                    'F2frequency_sma3nz_amean': 'F2 frequency M',
                    'F2frequency_sma3nz_stddevNorm': 'F2 frequency CV',
                    'F2bandwidth_sma3nz_amean': 'F2 bandwidth M',
                    'F2bandwidth_sma3nz_stddevNorm': 'F2 bandwidth CV',
                    'F2amplitudeLogRelF0_sma3nz_amean': 'F2 amplitude M',
                    'F2amplitudeLogRelF0_sma3nz_stddevNorm': 'F2 amplitude CV',
                    'F3frequency_sma3nz_amean': 'F3 frequency M',
                    'F3frequency_sma3nz_stddevNorm': 'F3 frequency CV',
                    'F3bandwidth_sma3nz_amean': 'F3 bandwidth M',
                    'F3bandwidth_sma3nz_stddevNorm': 'F3 bandwidth CV',
                    'F3amplitudeLogRelF0_sma3nz_amean': 'F3 amplitude M',
                    'F3amplitudeLogRelF0_sma3nz_stddevNorm': 'F3 amplitude CV',
                    'alphaRatioV_sma3nz_amean': 'Alpha ratio (voiced) M',
                    'alphaRatioV_sma3nz_stddevNorm': 'Alpha ratio (voiced) CV',
                    'hammarbergIndexV_sma3nz_amean': 'Hammarberg index (voiced) M',
                    'hammarbergIndexV_sma3nz_stddevNorm': 'Hammarberg index (voiced) CV',
                    'slopeV0-500_sma3nz_amean': 'Spectral slope 0-500 (voiced) M',
                    'slopeV0-500_sma3nz_stddevNorm': 'Spectral slope 0-500 (voiced) CV',
                    'slopeV500-1500_sma3nz_amean': 'Spectral slope 500-1500 (voiced) M',
                    'slopeV500-1500_sma3nz_stddevNorm': 'Spectral slope 500-1500 (voiced) CV',
                    'spectralFluxV_sma3nz_amean': 'Spectral flux (voiced) M',
                    'spectralFluxV_sma3nz_stddevNorm': 'Spectral flux (voiced) CV',
                    'mfcc1V_sma3nz_amean': 'MFCC1 (voiced) M',
                    'mfcc1V_sma3nz_stddevNorm': 'MFCC1 (voiced) CV',
                    'mfcc2V_sma3nz_amean': 'MFCC2 (voiced) M',
                    'mfcc2V_sma3nz_stddevNorm': 'MFCC2 (voiced) CV',
                    'mfcc3V_sma3nz_amean': 'MFCC3 (voiced) M',
                    'mfcc3V_sma3nz_stddevNorm': 'MFCC3 (voiced) CV',
                    'mfcc4V_sma3nz_amean': 'MFCC4 (voiced) M',
                    'mfcc4V_sma3nz_stddevNorm': 'MFCC4 (voiced) CV',
                    'alphaRatioUV_sma3nz_amean': 'Alpha ratio (unvoiced) M',
                    'hammarbergIndexUV_sma3nz_amean': 'Hammarberg index (unvoiced) M',
                    'slopeUV0-500_sma3nz_amean': 'Spectral slope 0-500 (unvoiced) M',
                    'slopeUV500-1500_sma3nz_amean': 'Spectral slope 500-1500 (unvoiced) M',
                    'spectralFluxUV_sma3nz_amean': 'Spectral flux (unvoiced) M',
                    'loudnessPeaksPerSec': 'Loudness peaks per second M',
                    'VoicedSegmentsPerSec': 'Voiced segments per second M',
                    'MeanVoicedSegmentLengthSec': 'Voiced segment length M',
                    'StddevVoicedSegmentLengthSec': 'Voiced segment length CV',
                    'MeanUnvoicedSegmentLength': 'Unvoiced segment length M',
                    'StddevUnvoicedSegmentLength': 'Unvoiced segment length CV',
                    'equivalentSoundLevel_dBp': 'Equivalent sound level M',
                    'AU01_r_mean': 'AU01 (inner brow raiser) M',
                    'AU01_r_stddevNorm': 'AU01 (inner brow raiser) CV',
                    'AU01_r_percentile20.0': 'AU01 (inner brow raiser) P20',
                    'AU01_r_percentile50.0': 'AU01 (inner brow raiser) P50',
                    'AU01_r_percentile80.0': 'AU01 (inner brow raiser) P80',
                    'AU01_r_iqr60_80-20': 'AU01 (inner brow raiser) P range',
                    'AU01_r_numPeaks': 'AU01 (inner brow raiser) N peaks',
                    'AU02_r_mean': 'AU02 (outer brow raiser) M',
                    'AU02_r_stddevNorm': 'AU02 (outer brow raiser) CV',
                    'AU02_r_percentile20.0': 'AU02 (outer brow raiser) P20',
                    'AU02_r_percentile50.0': 'AU02 (outer brow raiser) P50',
                    'AU02_r_percentile80.0': 'AU02 (outer brow raiser) P80',
                    'AU02_r_iqr60_80-20': 'AU02 (outer brow raiser) P range',
                    'AU02_r_numPeaks': 'AU02 (outer brow raiser) N peaks',
                    'AU04_r_mean': 'AU04 (brow lowerer) M',
                    'AU04_r_stddevNorm': 'AU04 (brow lowerer) CV',
                    'AU04_r_percentile20.0': 'AU04 (brow lowerer) P20',
                    'AU04_r_percentile50.0': 'AU04 (brow lowerer) P50',
                    'AU04_r_percentile80.0': 'AU04 (brow lowerer) P80',
                    'AU04_r_iqr60_80-20': 'AU04 (brow lowerer) P range',
                    'AU04_r_numPeaks': 'AU04 (brow lowerer) N peaks',
                    'AU05_r_mean': 'AU05 (upper lid raiser) M',
                    'AU05_r_stddevNorm': 'AU05 (upper lid raiser) CV',
                    'AU05_r_percentile20.0': 'AU05 (upper lid raiser) P20',
                    'AU05_r_percentile50.0': 'AU05 (upper lid raiser) P50',
                    'AU05_r_percentile80.0': 'AU05 (upper lid raiser) P80',
                    'AU05_r_iqr60_80-20': 'AU05 (upper lid raiser) P range',
                    'AU05_r_numPeaks': 'AU05 (upper lid raiser) N peaks',
                    'AU06_r_mean': 'AU06 (cheek raiser) M',
                    'AU06_r_stddevNorm': 'AU06 (cheek raiser) CV',
                    'AU06_r_percentile20.0': 'AU06 (cheek raiser) P20',
                    'AU06_r_percentile50.0': 'AU06 (cheek raiser) P50',
                    'AU06_r_percentile80.0': 'AU06 (cheek raiser) P80',
                    'AU06_r_iqr60_80-20': 'AU06 (cheek raiser) P range',
                    'AU06_r_numPeaks': 'AU06 (cheek raiser) N peaks',
                    'AU07_r_mean': 'AU07 (lid tightener) M',
                    'AU07_r_stddevNorm': 'AU07 (lid tightener) CV',
                    'AU07_r_percentile20.0': 'AU07 (lid tightener) P20',
                    'AU07_r_percentile50.0': 'AU07 (lid tightener) P50',
                    'AU07_r_percentile80.0': 'AU07 (lid tightener) P80',
                    'AU07_r_iqr60_80-20': 'AU07 (lid tightener) P range',
                    'AU07_r_numPeaks': 'AU07 (lid tightener) N peaks',
                    'AU09_r_mean': 'AU09 (nose wrinkler) M',
                    'AU09_r_stddevNorm': 'AU09 (nose wrinkler) CV',
                    'AU09_r_percentile20.0': 'AU09 (nose wrinkler) P20',
                    'AU09_r_percentile50.0': 'AU09 (nose wrinkler) P50',
                    'AU09_r_percentile80.0': 'AU09 (nose wrinkler) P80',
                    'AU09_r_iqr60_80-20': 'AU09 (nose wrinkler) P range',
                    'AU09_r_numPeaks': 'AU09 (nose wrinkler) N peaks',
                    'AU10_r_mean': 'AU10 (upper lip raiser) M',
                    'AU10_r_stddevNorm': 'AU10 (upper lip raiser) CV',
                    'AU10_r_percentile20.0': 'AU10 (upper lip raiser) P20',
                    'AU10_r_percentile50.0': 'AU10 (upper lip raiser) P50',
                    'AU10_r_percentile80.0': 'AU10 (upper lip raiser) P80',
                    'AU10_r_iqr60_80-20': 'AU10 (upper lip raiser) P range',
                    'AU10_r_numPeaks': 'AU10 (upper lip raiser) N peaks',
                    'AU12_r_mean': 'AU12 (lip corner puller) M',
                    'AU12_r_stddevNorm': 'AU12 (lip corner puller) CV',
                    'AU12_r_percentile20.0': 'AU12 (lip corner puller) P20',
                    'AU12_r_percentile50.0': 'AU12 (lip corner puller) P50',
                    'AU12_r_percentile80.0': 'AU12 (lip corner puller) P80',
                    'AU12_r_iqr60_80-20': 'AU12 (lip corner puller) P range',
                    'AU12_r_numPeaks': 'AU12 (lip corner puller) N peaks',
                    'AU14_r_mean': 'AU14 (dimpler) M',
                    'AU14_r_stddevNorm': 'AU14 (dimpler) CV',
                    'AU14_r_percentile20.0': 'AU14 (dimpler) P20',
                    'AU14_r_percentile50.0': 'AU14 (dimpler) P50',
                    'AU14_r_percentile80.0': 'AU14 (dimpler) P80',
                    'AU14_r_iqr60_80-20': 'AU14 (dimpler) P range',
                    'AU14_r_numPeaks': 'AU14 (dimpler) N peaks',
                    'AU15_r_mean': 'AU15 (lip corner depressor) M',
                    'AU15_r_stddevNorm': 'AU15 (lip corner depressor) CV',
                    'AU15_r_percentile20.0': 'AU15 (lip corner depressor) P20',
                    'AU15_r_percentile50.0': 'AU15 (lip corner depressor) P50',
                    'AU15_r_percentile80.0': 'AU15 (lip corner depressor) P80',
                    'AU15_r_iqr60_80-20': 'AU15 (lip corner depressor) P range',
                    'AU15_r_numPeaks': 'AU15 (lip corner depressor) N peaks',
                    'AU17_r_mean': 'AU17 (chin raiser) M',
                    'AU17_r_stddevNorm': 'AU17 (chin raiser) CV',
                    'AU17_r_percentile20.0': 'AU17 (chin raiser) P20',
                    'AU17_r_percentile50.0': 'AU17 (chin raiser) P50',
                    'AU17_r_percentile80.0': 'AU17 (chin raiser) P80',
                    'AU17_r_iqr60_80-20': 'AU17 (chin raiser) P range',
                    'AU17_r_numPeaks': 'AU17 (chin raiser) N peaks',
                    'AU20_r_mean': 'AU20 (lip stretcher) M',
                    'AU20_r_stddevNorm': 'AU20 (lip stretcher) CV',
                    'AU20_r_percentile20.0': 'AU20 (lip stretcher) P20',
                    'AU20_r_percentile50.0': 'AU20 (lip stretcher) P50',
                    'AU20_r_percentile80.0': 'AU20 (lip stretcher) P80',
                    'AU20_r_iqr60_80-20': 'AU20 (lip stretcher) P range',
                    'AU20_r_numPeaks': 'AU20 (lip stretcher) N peaks',
                    'AU23_r_mean': 'AU23 (lip tightener) M',
                    'AU23_r_stddevNorm': 'AU23 (lip tightener) CV',
                    'AU23_r_percentile20.0': 'AU23 (lip tightener) P20',
                    'AU23_r_percentile50.0': 'AU23 (lip tightener) P50',
                    'AU23_r_percentile80.0': 'AU23 (lip tightener) P80',
                    'AU23_r_iqr60_80-20': 'AU23 (lip tightener) P range',
                    'AU23_r_numPeaks': 'AU23 (lip tightener) N peaks',
                    'AU25_r_mean': 'AU25 (lips part) M',
                    'AU25_r_stddevNorm': 'AU25 (lips part) CV',
                    'AU25_r_percentile20.0': 'AU25 (lips part) P20',
                    'AU25_r_percentile50.0': 'AU25 (lips part) P50',
                    'AU25_r_percentile80.0': 'AU25 (lips part) P80',
                    'AU25_r_iqr60_80-20': 'AU25 (lips part) P range',
                    'AU25_r_numPeaks': 'AU25 (lips part) N peaks',
                    'AU26_r_mean': 'AU26 (jaw drop) M',
                    'AU26_r_stddevNorm': 'AU26 (jaw drop) CV',
                    'AU26_r_percentile20.0': 'AU26 (jaw drop) P20',
                    'AU26_r_percentile50.0': 'AU26 (jaw drop) P50',
                    'AU26_r_percentile80.0': 'AU26 (jaw drop) P80',
                    'AU26_r_iqr60_80-20': 'AU26 (jaw drop) P range',
                    'AU26_r_numPeaks': 'AU26 (jaw drop) N peaks',
                    'AU45_r_mean': 'AU45 (blink) M',
                    'AU45_r_stddevNorm': 'AU45 (blink) CV',
                    'AU45_r_percentile20.0': 'AU45 (blink) P20',
                    'AU45_r_percentile50.0': 'AU45 (blink) P50',
                    'AU45_r_percentile80.0': 'AU45 (blink) P80',
                    'AU45_r_iqr60_80-20': 'AU45 (blink) P range',
                    'AU45_r_numPeaks': 'AU45 (blink) N peaks'
                   }

feat_order_summary_audio = ['F0 M', 'F0 CV', 'F0 P20', 'F0 P80', 'F0 SD rising slope', 'Jitter M',
                            'F1 frequency M', 'F1 frequency CV', 'F1 bandwidth M', 'F2 frequency M',
                            'F2 frequency CV', 'F2 bandwidth CV', 'F3 frequency CV', 'F3 bandwidth M',
                            'F3 bandwidth CV', 'Loudness CV', 'Loudness P20', 'Loudness P range',
                            'Loudness M rising slope', 'Loudness SD rising slope', 'Loudness M falling slope',
                            'Harmonics to noise ratio M', 'Shimmer M', 'Equivalent sound level M',
                            'Alpha ratio (voiced) M', 'Alpha ratio (unvoiced) M', 'Hammarberg index (voiced) M',
                            'Hammarberg index (voiced) CV', 'Hammarberg index (unvoiced) M', 'Spectral slope 0-500 (voiced) M',
                            'Spectral slope 500-1500 (voiced) M', 'Spectral slope 0-500 (unvoiced) M',
                            'Spectral slope 500-1500 (unvoiced) M', 'Spectral flux CV', 'Spectral flux (voiced) M',
                            'Spectral flux (voiced) CV', 'F1 amplitude M', 'F2 amplitude M', 'F3 amplitude M',
                            'MFCC1 M', 'MFCC1 (voiced) M', 'MFCC2 M', 'MFCC2 (voiced) M', 'MFCC3 (voiced) M',
                            'MFCC3 (voiced) CV', 'MFCC4 (voiced) M', 'Loudness peaks per second M',
                            'Voiced segments per second M', 'Voiced segment length M', 'Voiced segment length CV']
                            
feat_order_summary_video = ['AU04 (brow lowerer) M', 'AU04 (brow lowerer) P20', 'AU04 (brow lowerer) P50', 'AU04 (brow lowerer) P80',
                            'AU06 (cheek raiser) M', 'AU06 (cheek raiser) P20', 'AU06 (cheek raiser) P50', 'AU06 (cheek raiser) P80',
                            'AU07 (lid tightener) M', 'AU07 (lid tightener) CV', 'AU07 (lid tightener) P50', 'AU07 (lid tightener) P80',
                            'AU10 (upper lip raiser) M', 'AU10 (upper lip raiser) CV', 'AU10 (upper lip raiser) P20',
                            'AU10 (upper lip raiser) P50', 'AU10 (upper lip raiser) P80', 'AU10 (upper lip raiser) P range',
                            'AU12 (lip corner puller) M', 'AU12 (lip corner puller) P50', 'AU12 (lip corner puller) P80',
                            'AU14 (dimpler) M', 'AU14 (dimpler) P20', 'AU14 (dimpler) P50', 'AU14 (dimpler) P80',
                            'AU15 (lip corner depressor) N peaks', 'AU17 (chin raiser) M', 'AU17 (chin raiser) P80',
                            'AU17 (chin raiser) N peaks', 'AU20 (lip stretcher) P80', 'AU23 (lip tightener) M', 'AU26 (jaw drop) M',
                            'AU26 (jaw drop) P range', 'AU26 (jaw drop) N peaks'
                            ]
                            
feat_order_summary_multi = ['F0 M', 'F0 CV', 'F0 P20', 'F0 P50', 'F0 P80', 'F0 P range', 'F0 SD rising slope', 'F0 SD falling slope',
                            'Loudness CV', 'Loudness P20', 'Loudness P50', 'Loudness P range', 'Loudness M rising slope',
                            'Loudness SD rising slope', 'Loudness M falling slope', 'Loudness SD falling slope', 'Spectral flux CV',
                            'MFCC1 M', 'MFCC2 M', 'Jitter M', 'Jitter CV', 'Shimmer M', 'Shimmer CV', 'Harmonics to noise ratio M',
                            'F1 frequency M','F1 frequency CV','F1 bandwidth M','F1 amplitude M','F2 frequency M','F2 frequency CV',
                            'F2 bandwidth M','F2 bandwidth CV','F2 amplitude M','F3 frequency CV','F3 bandwidth M','F3 bandwidth CV',
                            'F3 amplitude M','F3 amplitude CV','Hammarberg index (voiced) M','Spectral slope 0-500 (voiced) M',
                            'Spectral slope 500-1500 (voiced) M','Spectral flux (voiced) M','Spectral flux (voiced) CV',
                            'MFCC1 (voiced) M','MFCC2 (voiced) M','MFCC3 (voiced) M','MFCC3 (voiced) CV','MFCC4 (voiced) M',
                            'Alpha ratio (unvoiced) M','Hammarberg index (unvoiced) M','Spectral slope 0-500 (unvoiced) M',
                            'Spectral flux (unvoiced) M','Loudness peaks per second M','Voiced segment length CV',
                            'Unvoiced segment length CV','Equivalent sound level M','AU04 (brow lowerer) M','AU04 (brow lowerer) CV',
                            'AU04 (brow lowerer) P20','AU04 (brow lowerer) P50','AU04 (brow lowerer) P80','AU04 (brow lowerer) P range',
                            'AU04 (brow lowerer) N peaks','AU05 (upper lid raiser) N peaks','AU06 (cheek raiser) M',
                            'AU06 (cheek raiser) P80','AU06 (cheek raiser) P range','AU06 (cheek raiser) N peaks',
                            'AU07 (lid tightener) M','AU07 (lid tightener) CV','AU07 (lid tightener) P80',
                            'AU07 (lid tightener) P range','AU07 (lid tightener) N peaks','AU10 (upper lip raiser) M',
                            'AU10 (upper lip raiser) CV','AU10 (upper lip raiser) P20','AU10 (upper lip raiser) P50',
                            'AU10 (upper lip raiser) P80','AU10 (upper lip raiser) P range','AU10 (upper lip raiser) N peaks',
                            'AU12 (lip corner puller) M','AU12 (lip corner puller) P20','AU12 (lip corner puller) P50',
                            'AU12 (lip corner puller) P80','AU12 (lip corner puller) P range','AU12 (lip corner puller) N peaks',
                            'AU14 (dimpler) P50','AU14 (dimpler) P range','AU15 (lip corner depressor) N peaks','AU17 (chin raiser) CV',
                            'AU17 (chin raiser) P80','AU17 (chin raiser) P range','AU17 (chin raiser) N peaks','AU23 (lip tightener) M',
                            'AU25 (lips part) N peaks','AU45 (blink) CV']
